services:
  gallery-debbug-off:
    build: .
    image: vianagallery/gallery-api:develop
    ports:
      - 8080:8080
    working_dir: /app
    restart: always
    depends_on:
      - postgres
    environment:
      TEST_NAME: Version-3.1
      POSTGRES_URL: postgresql+psycopg2://postgres:example@postgres:5432/database
      ADMIN_JWT: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJtYXJjZWxvQGVtYWlsLmNvbSIsImV4cCI6MTcwMzQ1MTc2NH0.7H0tsroOtGhRmoixujPCqOb5w7fIB8YjTRkEnN88XCI
      # AZURE_STORAGE_CNN_STR: DefaultEndpointsProtocol=https;AccountName=01vianadev;AccountKey=Rv3sdophD7yqxfpuVdDdeyEANR0XJ9EpRRfjTn+pcjz4mPqbiYQRzeNdOJIPhyc8U5CWPXktvVNL+AStoT9SlA==;EndpointSuffix=core.windows.net
      CFI_ID: 396a1fd05689c45f07bdd191705e98dd
      CFI_TOKEN: aca-0JGeQfgqcseF1zDc5YSVf63Mp0Xs2cOtLv-J
    networks:
      - practice
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app/app
          ignore:
            - __pycache__/
        - action: rebuild
          path: package.json

  postgres:
    image: postgres
    restart: always
    volumes:
      - 03-gallery-postgres-data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432
    # env_file:
    #   - .env
    environment:
      POSTGRES_PASSWORD: example
      # POSTGRES_PASSWORD: fa738ce94be6106044d5dcb0b799deef23228c4bbf278d83196c4aacb4e2db9e
      POSTGRES_USER: postgres
      POSTGRES_DB: database
    networks:
        - practice

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - practice

volumes:
  03-gallery-postgres-data:
  
networks:
  practice: